version: '3.7'

x-shared-config: &shared_config
  environment:
    POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-scram-sha-256}"
    POSTGRES_USER: test_username
    POSTGRES_DB: test_database
    POSTGRES_PASSWORD: test_password
  ports:
    - 5432:5432

services:
  psql-15:
    image: postgres:15
    <<: *shared_config
